### ISSUE TITLE
Bug: Lualine dissappears when sourcing config file

### ISSUE THREAD

**Issue by jeanlucthumm** [hoob3rt/lualine.nvim#320] opened 2021-08-23 01:07 UTC
https://user-images.githubusercontent.com/4934853/130376677-42c4b395-db5d-4970-a178-7254932ae584.mp4

### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
```
> nvim --version 
NVIM v0.6.0-dev+112-ge7bde44d6
```
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. Use this config file, save as `~/sample.lua`:
```
require "paq" {
    "savq/paq-nvim",
    "hoob3rt/lualine.nvim",
}

require"lualine".setup {}

vim.api.nvim_set_keymap("n", "<F5>", ":source ~/sample.lua<CR>", {noremap = true})
```
2. Install [paq](https://github.com/savq/paq-nvim)
3. Open `nvim`, run `:PaqInstall` and exit
4. Issue `nvim -u ~/sample.lua ~/sample.lua`
5. Press `<F5>`

### Actual behaviour

6. Lua line disappears

### Expected behaviour

6. Lua line does not dissappear

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

require "paq" {
    "savq/paq-nvim",
    "hoob3rt/lualine.nvim",
}

require"lualine".setup {}

vim.api.nvim_set_keymap("n", "<F5>", ":source ~/sample.lua<CR>", {noremap = true})

</details>

**Comment by shadmansaleh** [comment] 2021-08-23 01:22
duplicate of #276.

fixed in #311
use [shsdmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim)

**Closed** 2021-08-23 01:45 UTC
Labels: bug
