### ISSUE TITLE
Bug: Lualine does not load after recent updates

### ISSUE THREAD

**Issue by rmagatti** [hoob3rt/lualine.nvim#208] opened 2021-05-03 04:21 UTC
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Loading the plugin with these configs on the latest commit does not work, as in lualine just doesn't load.
```lua
require('lualine').setup{
  theme = 'gruvbox',
  extensions = { 'fzf', 'fugitive' },
}
```

Everything works fine however if I rollback to this commit https://github.com/hoob3rt/lualine.nvim/commit/6ba2b80b594c3ead11ab9bd1dbc94c0b4ea46c33

### Actual behaviour
Lualine doesn't load.

### Expected behaviour
Lualine loads :)

### Minimal config to reproduce the issue
I don't have one but let me know if you can't reproduce and I can try and provide one.

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment] 2021-05-03 05:18
Lualine loads but you don't have any components in any of the sections so it's not displaying anything . It's a intended behavior. Previously the components defined in user config would extend the default . That causes conflicts and extra boilarplate when you want to omit some  sections. So the behavior was changed in f08e8514ddbe73cb02644cbd7b4b98e3681a7f9d .Now default sections don't get applied if you provide configuration (by passing a table to setup function or by g:lualine) . In short `require'lualine'.setup()` would load the default sections but `require'lualine'.setup({})` won't . If you want the default components just copy paste the [default config](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/defaults.lua) . If you think your issue is resolved then close the issue :)

**Comment by goolord** [comment] 2021-05-03 13:19
i suppose if you want the defaults to be managed for you you could write
```lua
sections = require'lualine.defaults'.sections,
inactive_sections = require'lualine.defaults'.inactive_sections
```
for as long as that works :d

**Comment by sdemura** [comment] 2021-05-03 14:21
Might I suggest that `README.md` be updated to reflect this change?

**Comment by michzappa** [comment] 2021-05-03 14:28
I have also been trying to figure this out for a bit. This is what I have following @shadmansaleh's advice of copying in the default config.
```lua
  use { 'hoob3rt/lualine.nvim',
        config = function()
          require('lualine').setup {
            options = {
              theme = 'auto',
              icons_enabled = false,
              section_separators = '',
              component_separators = '',
              disabled_filetypes = {}
            },
            sections = {
              lualine_a = {'mode'},
              lualine_b = {'branch'},
              lualine_c = {'filename'},
              lualine_x = {'encoding', 'fileformat', 'filetype'},
              lualine_y = {'progress'},
              lualine_z = {'location'}
            },
            inactive_sections = {
              lualine_a = {},
              lualine_b = {},
              lualine_c = {'filename'},
              lualine_x = {'location'},
              lualine_y = {},
              lualine_z = {}
            },
            tabline = {},
            extensions = {}
          }
        end
  }
```
However, lualine still does not load. The only custom configuration I really want is no separator icons. Am I handling the table wrong? Thank you

**Comment by goolord** [comment] 2021-05-03 14:32
@michzappa your config works fine for me. have you run `:PackerCompile`?

**Comment by michzappa** [comment] 2021-05-03 14:33
Wow, I have done that before but completely neglected doing so now. Thank you for reminding me.

**Comment by shadmansaleh** [comment] 2021-05-03 15:02
> i suppose if you want the section defaults to be managed for you you could write
```lua
sections = require'lualine.defaults'.sections,
inactive_sections = require'lualine.defaults'.inactive_sections
for as long as that works :d
```
That will work for now but I won't recommend it as it's a internal file and can be moved/removed/changed without notice . That will break the config :)

> Might I suggest that README.md be updated to reflect this change?

Yes you might . But It's not a advertised use case in my opinion . There's actually config example in both lua and vimL so users can copy them and make changes as they like , The defaults in defaults.lua is there to make it easy to try lualine for the first time I think . Can you suggest where that should go in README ? Since it was never recomanded to rely on defaults . We could probably have a section in README listing breaking behavioral changes like packer.

> Wow, I have done that before but completely neglected doing so now. Thank you for reminding me

Yeah that gets everyone time to time :D
At least wbthomason [working](https://github.com/wbthomason/packer.nvim#current-work-in-progress) on making PackerCompile unnecessary .

**Comment by goolord** [comment] 2021-05-03 15:10
> Since it was never recommended to rely on defaults

I think this conflicts with the way most people interact with configuring vim plugins. Most are probably familiar with the workflow of incrementally changing only the options which are relevant to them. This way changes to the plugin affect users minimally, and there's little cognitive overhead. It might be unexpected that changing 1 or few options in `setup` changes the defaults for every option. Just my 2 cents

**Comment by shadmansaleh** [comment] 2021-05-03 17:30
> I think this conflicts with the way most people interact with configuring vim plugins.
>
> Most are probably familiar with the workflow of incrementally changing only the options which are relevant to them. This way changes to the plugin affect users minimally, and there's little cognitive overhead.

This makes me think I use plugins weirdly :D .As I always  copy paste configs and tweak them later . But I can see your point .

To be honest my main annoyence was having to do this to disable inactive status

```
inactive_sections = {
              lualine_a = {},
              lualine_b = {},
              lualine_c = {},
              lualine_x = {},
              lualine_y = {},
              lualine_z = {}
            },
```
And this issue with evil_lualine got my attention :)
![Screenshot](https://user-images.githubusercontent.com/33150416/116790054-a1c6e800-aab2-11eb-85c6-ac1769b9a295.png)

**Comment by goolord** [comment] 2021-05-03 17:36
i think i've seen a pattern like `x.enable_defaults = false` in the wild

**Comment by GenesisTMS** [comment] 2021-05-03 19:58
At least would be nice to have smth like lsp have for customizing handlers -> `vim.lsp.with` s o you can edit single option without copy&paste all defaults which IMHO is bad practice because if you someday touch defaults - none will figure out or it may break.

so smth like: `lualine.setup(lualine.defaults({sections = { lualine_c = {'xxx'}))`
Or somehow make defaults properly accessible from code and not from readme.

Thanks for plugin btw, really enjoying so far!

**Comment by shadmansaleh** [comment] 2021-05-03 22:21
I think I'm pretty convinced to revert the changes :]

**Closed** 2021-05-03 23:03 UTC
Labels: bug

**Comment by shadmansaleh** [comment] 2021-05-03 23:04
Now you guys can go back to enjoying default config like before :D
