### ISSUE TITLE
Change filename highlighting depending on status

### ISSUE THREAD

**Issue by starmatt** [hoob3rt/lualine.nvim#335] opened 2021-09-09 15:25 UTC
Hello, would it possible to add a different highlighting for the `filename` component, depending on its status ? For example, have the file name be gray when untouched (or saved), but turn white and italic when modified.
I find it's a nice way to tell quickly that the file was modified (moreso than the `[+]` symbol).

Thanks for your attention, this plugin is great!

**Comment by shadmansaleh** [comment] 2021-09-09 15:37
Duplicate of https://github.com/hoob3rt/lualine.nvim/issues/315

You should search the issue tracker first.

**Comment by starmatt** [comment] 2021-09-09 17:57
Hi, thanks for the speedy answer!
You're right, I should've searched (I did but I wasn't thorough enough apparently!)

The snippet you shared with me has too many limitations, it breaks nearby components highlighting, and doesn't do enough as said in the issue you linked.
However the patched `filename.lua` works pretty well. I put it in  `~/.config/nvim/lua/lualine/components/filename.lua`, but I don't really like having to overwrite specific parts of plugins in my nvim config.
I know I could make a fork, but it isn't worth it to me for such a small feature, and I feel that it doesn't really go with the 'easy to customize' philosophy of this plugin.

Now, I'm pretty noob at Lua still and the nvim api and how it all clicks, so if you happen to have some sort of inbetween solution for me that'd be great. Otherwise I guess you (or I) can close this issue.

Thanks again!

**Comment by shadmansaleh** [comment] 2021-09-09 18:40
inspirit of OOP you can create a component by inheriting   from an existing component . That way you won't have to patch the existing component. Instead just extend the `new` and `update_status` method in your component .

All the components are built by inheriting from base component class you can just follow that pattern instead of base class inherit from the filename class.

You'll have access to the super/parrent class in your own components `_parent` key.

I guess that would be less hacky.

**Comment by starmatt** [comment] 2021-09-09 23:03
That's great, for this to work I would have to put the custom component in `~/.config/nvim/lua/lualine/components` right ? Or can I put it somewhere else ? If so, how do I link it to my lualine config ?

Here's what I got so far but I think I am missing something (or being able to put it along the rest of my lualine config just might not be possible...)

Here's my config tree (shortened):
```
.config/nvim/
├── init.lua
├── lua
│   ├── keymappings.lua
│   ├── plugins
│   │   ├── plugin_conf.lua
│   │   ├── another_plugin_conf.lua
│   │   ├── init.lua
│   │   ├── ...
│   │   ├── lualine
│   │   │   ├── init.lua         <~~ My lualine setup function
│   │   │   └── filename.lua     <~~ Where I would like my custom filename to go
│   │   ├── ...
│   │   └── some_other_plugin.lua
│   ├── settings.lua
│   └── utils.lua
└── plugin
    └── packer_compiled.lua
```

My custom filename:
```lua
local hl = require('lualine.highlight')
local colors = require('starmatt.colors')

local FileName = require('lualine.components.filename'):new()

FileName.new = function(self, options, child)
    local new_instance = self._parent:new(options, child or FileName)

    new_instance.status_colors = {
        saved = hl.create_component_highlight_group(
            { fg = nil },
            'filename_status_saved',
            new_instance.options
        ),
        modified = hl.create_component_highlight_group(
            { fg = colors.fg },
            'filename_status_modified',
            new_instance.options
        ),
        readonly = hl.create_component_highlight_group(
            { fg = colors.red },
            'filename_status_readonly',
            new_instance.options
        ),
    }

    return new_instance
end

FileName.update_status = function(self)
    local data = self._parent:update_status()

    if self.options.file_status then
        if vim.bo.modified then
            data = hl.component_format_highlight(self.status_colors.modified) .. data
        elseif vim.bo.modifiable == false or vim.bo.readonly == true then
            data = hl.component_format_highlight(self.status_colors.readonly) .. data
        else
            data = hl.component_format_highlight(self.status_colors.saved) .. data
        end
    end

    return data
end

return FileName
```

My lualine setup function
```lua
local FileName = require('plugins.lualine.filename')

local sections = {
    lualine_a = { 'mode' },
    lualine_b = { 'branch' },
    lualine_c = { FileName:new() }, --      <~~ This isn't right...
    lualine_x = { 'encoding', 'fileformat', 'filetype' },
    lualine_y = { 'progress'},
    lualine_z = { 'location'}
}

require('lualine').setup({
    options = { theme = 'starmatt' },
    sections = vim.deepcopy(sections),
    inactive_sections = vim.deepcopy(sections),
})
```

I hope I'm being clear!
Again thanks, at least I'm learning some new stuff :grin:

**Comment by shadmansaleh** [comment] 2021-09-10 06:49
You must have it on `~/.config/nvim/lua/lualine/components` as that's where lualine will search for it .You could try placing a dummy file containing something like this to redirect it to your plugin folder'
```lua
return require'plugins.lualine.filename'
```

Also you need to just specify the component name in string like other components like.
```lua
lualine_c = { 'my_filename' },
```

**Comment by starmatt** [comment] 2021-09-10 08:40
I'm having trouble when instanciating the parent:
```lua
local FileName = require('lualine.components.filename'):new()
```
This fails silently (the component just doesn't show)
I tried `return require('lualine.components.filename'):new()`, to check if the issue could come from my custom code, but it has the same result.

I've also tried:
```lua
local FileName = require('lualine.components.filename')
```
which gives me this error:
`E5108: Error executing lua .../.config/nvim/lua/lualine/components/filename_custom.lua:33: attempt to index field 'options' (a nil value)`

Any idea ? Thanks again for your help!

**Comment by shadmansaleh** [comment] 2021-09-10 09:16
Try this for now

```lua
local FileName = require('lualine.components.filename')
local MyFileName = FileName:new()

local highlight = require'lualine.highlight'
local default_status_colors = {
  saved = '#228B22',
  modified = '#C70039'
}

function MyFileName:new(options, child)
  local new_instance = self._parent:new(options, child or MyFileName)
  new_instance.status_colors = {
    saved = highlight.create_component_highlight_group(
      {bg = default_status_colors.saved}, 'filename_status_saved', new_instance.options),
    modified = highlight.create_component_highlight_group(
      {bg = default_status_colors.modified}, 'filename_status_modified', new_instance.options),
  }
  -- Hack to remove sep lualine should auto remove the sep
  if new_instance.options.color == nil then new_instance.options.color = '' end
  return new_instance
end

local parent_updater = FileName.update_status -- Hack to access parents
                                              -- updater. There's something wrong with _parent
                                              -- Inheritence should be done by separate function not new

function MyFileName:update_status()
  local data = parent_updater(MyFileName)
  data = highlight.component_format_highlight(vim.bo.modified
                                              and self.status_colors.modified
                                              or self.status_colors.saved) .. data
  return data
end

return MyFileName
```

There's a few thing that lualine should internally support to remove the hacky part in this implementation . Currently I'm too busy to hunt them down . But this should do the job.

**Closed** 2021-09-13 13:28 UTC
Labels: new feature
